pretrained_model_name_or_path = "E:/ComfyUI-aki-v1.4/models/checkpoints/SDXL/sd_xl_base_1.0.safetensors"
train_data_dir = "E:/durian_leaf_disease/lora_train_sdxl/Leaf_Spot"
prior_loss_weight = 1
resolution = "512,512"
enable_bucket = true
min_bucket_reso = 256
max_bucket_reso = 1024
bucket_reso_steps = 64
bucket_no_upscale = true
output_name = "leaf_spot_r64"
output_dir = "D:/lora-scripts-outputs/sdxl"
save_model_as = "safetensors"
save_precision = "bf16"
save_every_n_epochs = 2
save_state = false
max_train_epochs = 10
train_batch_size = 1
gradient_checkpointing = false
network_train_unet_only = true
network_train_text_encoder_only = false
learning_rate = 5e-5
unet_lr = 5e-5
text_encoder_lr = 5e-6
lr_scheduler = "cosine_with_restarts"
lr_warmup_steps = 0
lr_scheduler_num_cycles = 1
optimizer_type = "AdamW8bit"
network_module = "networks.lora"
network_dim = 64
network_alpha = 64
log_with = "tensorboard"
logging_dir = "./logs"
caption_extension = ".txt"
shuffle_caption = true
keep_tokens = 1
max_token_length = 255
caption_dropout_rate = 0.1
caption_tag_dropout_rate = 0.1
color_aug = true
flip_aug = true
random_crop = true
seed = 1337
mixed_precision = "bf16"
full_bf16 = true
no_half_vae = true
xformers = true
sdpa = true
lowram = false
cache_latents = false
cache_latents_to_disk = false
persistent_data_loader_workers = true
