pretrained_model_name_or_path = "E:/ComfyUI-aki-v1.4/models/unet/SD3.5/sd3.5_large.safetensors"
clip_l = "E:/ComfyUI-aki-v1.4/models/clip/SD3.5/clip_l.safetensors"
clip_g = "E:/ComfyUI-aki-v1.4/models/clip/SD3.5/clip_g.safetensors"
t5xxl = "E:/ComfyUI-aki-v1.4/models/clip/SD3.5/t5xxl_fp8_e4m3fn.safetensors"
train_t5xxl = false
train_data_dir = "E:/durian_leaf_disease/lora_train_sd35/Leaf_Spot"
prior_loss_weight = 1
resolution = "512,512"
enable_bucket = true
min_bucket_reso = 256
max_bucket_reso = 2048
bucket_reso_steps = 64
bucket_no_upscale = true
output_name = "leaf_spot_r64"
output_dir = "D:/lora-scripts-outputs/sd35"
save_model_as = "safetensors"
save_precision = "bf16"
save_every_n_epochs = 2
save_state = false
max_train_epochs = 20
train_batch_size = 1
gradient_checkpointing = true
gradient_accumulation_steps = 1
network_train_unet_only = true
network_train_text_encoder_only = false
learning_rate = 5e-5
unet_lr = 5e-5
text_encoder_lr = 5e-6
lr_scheduler = "cosine_with_restarts"
lr_warmup_steps = 0
lr_scheduler_num_cycles = 1
optimizer_type = "AdamW8bit"
network_module = "networks.lora_sd3"
network_dim = 64
network_alpha = 64
log_with = "tensorboard"
logging_dir = "./logs"
caption_extension = ".txt"
shuffle_caption = false
keep_tokens = 1
caption_dropout_rate = 0.1
caption_tag_dropout_rate = 0.1
color_aug = true
flip_aug = true
random_crop = true
seed = 1337
clip_skip = 2
mixed_precision = "bf16"
full_bf16 = true
no_half_vae = true
sdpa = true
lowram = false
cache_latents = false
cache_latents_to_disk = false
cache_text_encoder_outputs = false
cache_text_encoder_outputs_to_disk = false
persistent_data_loader_workers = true
fp8_base = true
